### ISSUE TITLE
Pb ansible/Docker

### ISSUE THREAD

**Issue by DamienGilles** [Yannig/meetup-ansible-paris-9#1]
Bonjour,
je viens de regarder votre présentation ma fois somme toutes très intéressante mais lors de la mise en pratique de votre lab je rencontre un souci. 
Lors de l'execution de la commande :  ansible-playbook -i inventory/single playbooks/install-mediawiki.yml 

Voici le message d'erreur... 
PLAY [Création de l'image + container docker] ************************************************************************

TASK [Construction des images centos] ********************************************************************************
ok: [localhost] => (item=centos-systemd)

TASK [Création du network] *******************************************************************************************
ok: [localhost]

TASK [Creation des containers] ***************************************************************************************
failed: [localhost] (item=dock-mysql) => {"changed": false, "item": "dock-mysql", "msg": "Error getting network id fore, 'Name': 'demo', 'Created': '2018-10-12T15:55:56.591460116+02:00', 'IPAM': {'Driver': 'default', 'Config': [{'Subnet', 'Gateway': '172.18.0.1'}], 'Options': None}, 'Labels': {}, 'EnableIPv6': False, 'Id': 'f3d57f41331af2525ea45d3494d2bbed376f6cd66a9d63b', 'ConfigOnly': False, 'Internal': False, 'ConfigFrom': {'Network': ''}, 'Options': {}, 'Driver': : 'local', 'Attachable': False, 'Containers': {}} - 500 Server Error: Internal Server Error (\"{\"message\":\"json: caray into Go value of type map[string]bool\"}\")"}
failed: [localhost] (item=dock-apache) => {"changed": false, "item": "dock-apache", "msg": "Error getting network id flse, 'Name': 'demo', 'Created': '2018-10-12T15:55:56.591460116+02:00', 'IPAM': {'Driver': 'default', 'Config': [{'Subn16', 'Gateway': '172.18.0.1'}], 'Options': None}, 'Labels': {}, 'EnableIPv6': False, 'Id': 'f3d57f41331af2525ea45d3494d9bbed376f6cd66a9d63b', 'ConfigOnly': False, 'Internal': False, 'ConfigFrom': {'Network': ''}, 'Options': {}, 'Driver'e': 'local', 'Attachable': False, 'Containers': {}} - 500 Server Error: Internal Server Error (\"{\"message\":\"json: array into Go value of type map[string]bool\"}\")"}

N'étant pas expert en la matière et en formation sur ces outils, je vais continuer mes investigations mais si vous pouvez m'aider, j'en serai ravi. 
Merci,
Damien.

**Comment by DamienGilles** [comment]
J'ai oublié les versions: 
[root@calypso meetup-ansible-paris-9]# ansible --version 
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@calypso meetup-ansible-paris-9]# docker --version 
Docker version 18.06.1-ce, build e68fc7a
[root@calypso meetup-ansible-paris-9]# 
docker-py                        1.10.6

**Comment by Yannig** [comment]
Bonjour,

Désolé pour la réponse un peu tardive ...

Il s'agit d'un conflit de variable avec docker_network. J'ai corrigé les playbooks de manière à faire appel à docker_network_name.
